AHC_DEV_05/AHC_DEV_05/Controllers/User/MainController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dao.User;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.User
{
    public class MainController : Controller
    {
        Permission checkuser = new Permission();
        // GET: main
        public ActionResult Index()
        {
            checkuser.chkrights("user");
            ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);
            var pm = GetDataDao.Instance.GetProductMember();
            ViewBag.PM = pm;

            int rows = Util.NVLInt(ConfigurationManager.AppSettings["rows"]);
            var data = OrderDao.Instance.GetOrderHis();
            var order = OrderDao.Instance.GetProductOrder(0, "");
            ViewBag.his_tb = data;
            ViewBag.cnt = data.Count();

            var interests = InterestDao.Instance.GetDataInterest().Find(smodel => smodel.id == Util.NVLString(Varible.User.member_id));
            ViewBag.interests = interests == null ? "0" : interests.interest.ToString();

            var model = MemberListDao.Instance.GetDataList().Find(smodel => smodel.id == Varible.User.member_id);
            decimal point = (GetDataDao.Instance.GetPointAmount(Varible.User.member_id) - Util.NVLInt(Varible.Config.register_point));
            ViewBag.amountCW = point.ToString("0,0", CultureInfo.InvariantCulture) + " Point  (￦ " + (point * Util.NVLDecimal(Varible.Config.jewel_price)).ToString("0,0", CultureInfo.InvariantCulture) + ")";
            ViewBag.point = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);


            //var dataNotice = NoticeDao.Instance.GetDataQA();
            //ViewBag.dataNotice = dataNotice;
            //ViewBag.cntNotice = dataNotice.Count();
            int? page = null;
            var dataNotice = ContentListDao.Instance.GetDataList();
            ViewBag.dataNotice = dataNotice.ToList().ToPagedList(page ?? 1, Util.NVLInt(ConfigurationManager.AppSettings["rows"]));
            ViewBag.cntNotice = dataNotice.Count();
            return View(order);

            
        }
    }
}

AHC_DEV_05/AHC_DEV_05/Controllers/User/OrderController.cs
using AHCBL.Component.Common;
using AHCBL.Dao;
using AHCBL.Dao.Admin;
using AHCBL.Dao.User;
using AHCBL.Dto;
using AHCBL.Dto.Admin;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AHC_MLK.Controllers.User
{
    public class OrderController : Controller
    {
        Permission checkuser = new Permission();

        //[HttpGet]
        public ActionResult Index(string token, string status, int? page)
        {
            checkuser.chkrights("user");
            ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);// Varible.User.amount;
                                                                                   //var data = ProductDao.Instance.GetProductOrder(1);
                                                                                        //var data = OrderDao.Instance.GetProductOrder(1);
            int rows = Util.NVLInt(ConfigurationManager.AppSettings["rows"]);
            ViewBag.rows = rows;

            int id = 0;
            if (token != null)
            {
                id = Util.NVLInt(DataCryptography.Decrypt(token));
            }
            var data = OrderDao.Instance.GetProductOrder(id, status);
            return View(data);

            //return View(data.ToList().ToPagedList(page ?? 1, Util.NVLInt(rows)));
            //var data = OrderDao.Instance.GetProductOrder(1).Find(smodel => smodel.id == id);
            //    return View(data);
            //return View(data);
        }
        public ActionResult Sell_list()
        {
            checkuser.chkrights("user");
            ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);// Varible.User.amount;
            //var data = ProductDao.Instance.GetProductOrder(2);
            var data = OrderDao.Instance.GetProductSaleOrder(0, "", "sale");
            return View(data);
        }
        public ActionResult Order_have()
        {
            checkuser.chkrights("user");
            var data = OrderDao.Instance.GetProductOrder(0, "");
            return View(data);
        }
        public ActionResult Order_buy_point()
        {
            checkuser.chkrights("user");
            ViewBag.bank_info = Varible.Config.bank_info;
            //var bank = DropdownDao.Instance.GetDataBank().Find(smodel => smodel.id == Varible.User.member_id);
            ViewBag.product_amt = Varible.Config.jewel_price.Replace(".00", "");// ConfigurationManager.AppSettings["product_amt"];
            ViewBag.exchange = Varible.Config.exchange.Replace(".00", ""); //Util.NVLDecimal(Varible.Config.exchange).ToString("0,0", CultureInfo.InvariantCulture);
            ViewBag.bank_info = Varible.Config.bank_info;// ConfigurationManager.AppSettings["bank_info"];
            ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id); //Varible.User.amount;
            ViewBag.product_qty = DropdownDao.Instance.GetDataPoint();
            ViewBag.txt1 = Varible.Config.txt1;
            ViewBag.bank_acc = Varible.Config.bank_acc; 

            return View();

        }

        public ActionResult BuyChip(string buy_name, int point, int amount, int price, int pay_type)
        {
            try
            {

                PointListDto model = new PointListDto();
                model.username = buy_name;
                model.name = "이체";
                model.pay_type = pay_type;
                model.amount = Util.NVLString(amount);
                model.price = Util.NVLString(price);
                model.total = Util.NVLString((point + amount));
                string result = PointListDao.Instance.SaveDataList(model, "mony");
                if (result != "OK")
                {
                    return Json(result);
                }
                else
                {
                    return Json("Successfully !");
                }

            }
            catch (Exception e)
            {
                return Json("Error !!");
            }
        }
        public ActionResult Order_send_point()
        {
            checkuser.chkrights("user");
            ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);
            return View();
        }
        public ActionResult TranPoint(int point, string pass)
        {
            try
            {
                if (pass != Varible.User.pass)
                {
                    return Json(new returnsave { err = "1", errmsg = "비밀번호가 일치하지 않습니다." });
                }
                else
                {
                    int p_id = Util.NVLInt(Session["member_id"]);
                    string result = PointListDao.Instance.TranPoint(0, point, p_id, "");
                    if (result != "OK")
                    {
                        return Json(new returnsave { err = "1", errmsg = "Error" });
                    }
                    else
                    {
                        return Json(new returnsave { err = "0", errmsg = "꿀벌 전송이 완료되었습니다." });
                    }
                }
            }
            catch (Exception e)
            {
                return Json(new returnsave { err = "1", errmsg = "Error" });
            }
        }
        public ActionResult ChkUserID(string pUid)
        {
            try
            {

                int member_id = 0;
                string pUName = string.Empty;
                int member_level = 0;
                string password = string.Empty;
                string amount = string.Empty;
                Session.Remove("member_id");
                bool result = LoginDao.Instance.ChkAuthDB(pUid, ref member_id, ref pUName, ref member_level, ref password, ref amount);
                if (result == false)
                {
                    return Json(new returnsave { err = "1", errmsg = "회원을 찾을수 없습니다." });
                }
                else
                {
                    Session["member_id"] = member_id;
                    return Json(new returnsave { err = "0", errmsg = "아이디가 확인되었습니다.\n꿀벌 전송을 진행해주세요." });
                }
            }
            catch (Exception e)
            {
                return Json(new returnsave { err = "0", errmsg = "Error" });
            }


            //return objreturnsave;
        }
        public ActionResult Order_list_point(int? page)
        {
            checkuser.chkrights("user");
            int rows = Util.NVLInt(ConfigurationManager.AppSettings["rows"]);
            var data = ProductDao.Instance.GetOrderList();
            return View(data.ToList().ToPagedList(page ?? 1, rows));
        }
        public ActionResult Sell_apply(string Token)
        {
            checkuser.chkrights("user");
            try
            {
                int id = Util.NVLInt(DataCryptography.Decrypt(Token));
                var data = OrderDao.Instance.GetProductSaleAppv(id);
                if (data.tab2.Count != 0)
                {
                    return View(data);
                }
                else
                {
                    ViewBag.amount = GetDataDao.Instance.GetPointAmount(Varible.User.member_id);// Varible.User.amount;
                                                                                                //var data = ProductDao.Instance.GetProductOrder(2);
                    data = OrderDao.Instance.GetProductOrder(0, "");
                    return View("~/Views/Order/Sell_list.cshtml", data);
                    //return View(data);
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }
        public ActionResult Order_apply(string Token)
        {
            checkuser.chkrights("user");
            try
            {
                int id = Util.NVLInt(DataCryptography.Decrypt(Token));
                var data = OrderDao.Instance.GetProductSale(id);
                if (data.tab2.Count == 0)
                {
                    return RedirectToAction("Matching");
                }
                return View(data);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }
        public ActionResult Matching()
        {
            return View();

        }
        public ActionResult Appv(int orderId, string buy_info, string token)
        {
            try
            {
                int id = Util.NVLInt(DataCryptography.Decrypt(token));
                string result = OrderDao.Instance.SaveData(orderId, id, buy_info, buy_info == "" ? "apv" : "buy");
                string chk = buy_info == "" ? "apv" : "";
                if (result != "OK")
                {
                    return Json(new returnsave { err = "1", errmsg = "Error" });
                }
                else
                {
                    if (chk == "apv")
                    {
                        var data = OrderDao.Instance.GetUserdata(orderId);
                        int cnt = 0;
                        for (int i = 0; i < data.Count; i++)
                        {
                            //if (data[i].id < Util.NVLInt(Varible.User.member_id))
                            //{
                            if (cnt == 0)
                            {
                                OrderDao.Instance.SaveInterest(orderId, 5);
                            }
                            else if (cnt == 1)
                            {
                                OrderDao.Instance.SaveInterest(orderId, 4);
                            }
                            else if (cnt == 2)
                            {
                                OrderDao.Instance.SaveInterest(orderId, 3);
                            }
                            else if (cnt == 3)
                            {

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_Error.cshtml
<!DOCTYPE html>
<html>
<head>
    @*<meta charset="utf-8" />*@
    <meta http-equiv=Content-Type content="text/html; charset=tis-620">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 장미나라</title>
    <link rel="icon" href="/vendor/images/logo.ico" type="image/x-icon" sizes="16x16">
    @Styles.Render("~/Content/css")
</head>
<body class="xp-vertical">

    <div class="xp-authenticate-bg"></div>
    <!-- Start XP Container -->
    <div id="xp-container" class="xp-container">
        @RenderBody()
    </div>
    <!-- End XP Container -->
</body>
</html>

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_Main.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>태왕의사신기</title>
    <link rel="icon" href="../../common/image/logo.ico" type="image/gif" sizes="16x16">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    @Styles.Render("~/common/css/pages/style.css")
    @Styles.Render("~/common/css/main.css")
    @Scripts.Render("~/common/script/jquery-3.4.1.min.js")
</head>
<body style="background-image: url('../../common/image/bg-page.jpg');background-position: center;">
    <div id="wrap" >
        <div class="container">
            <div class="dash-profile">
                <a class="tab" href="@Url.Action("Index","Main")" data-aos="fade-down" data-aos-duration="2000">
                    <span class="language">&nbspHOME</span>
                </a>
                <a class="tab" href="@Url.Action("Order_buy_point","Order")" data-aos="fade-down" data-aos-duration="2000">
                    <span class="language">신청하기</span>
                </a>
                <a class="tab" href="~/Login/LogOut" data-aos="fade-down" data-aos-duration="2000">
                    <span class="language">로그아웃</span>
                </a>
            </div>

            @RenderBody()
        </div>
    </div>

    <input type="text" value="@Session["url"]" class="urlJoin" style="position:absolute;left:-1000px;top:-1000px;" />

    <script type="text/javascript">
        document.querySelector(".copy").addEventListener("click", copyText);
        function copyText() {
            var copyText = document.querySelector(".urlJoin");
            copyText.select();
            copyText.setSelectionRange(0, 99999);
            document.execCommand("copy");
            alert("복사 된 텍스트 : " + copyText.value);
        }
    </script>

    @Scripts.Render("~/common/script/Chart.min.js")
    @Scripts.Render("~/common/script/all.js")
    @Scripts.Render("~/common/script/jquery.custom.extend.js")
    @Scripts.Render("~/common/script/commonutil.js")
    @Scripts.Render("~/common/script/jquery.cookie.js")
    @Scripts.Render("~/common/script/clipboard.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_Main_Matching.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyOffice</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    @Styles.Render("~/common/css/pages/style.css")
    @Styles.Render("~/common/css/main.css")
    @Scripts.Render("~/common/script/jquery-3.4.1.min.js")
</head>
<body style="background-image: url('../../common/image/bg-page.png');background-size: cover;">
    <div>
        <div class="container">

            @RenderBody()
        </div>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_Product.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>태왕의사신기</title>
    <link rel="icon" href="../../common/image/logo.ico" type="image/gif" sizes="16x16">
    <!-- Alert Modal -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    @Styles.Render("~/common/css/pages/style.css")
    @Styles.Render("~/common/css/main.css")
    @Styles.Render("~/common/css/reset-1.css")
    @Scripts.Render("~/common/script/jquery-3.4.1.min.js")
</head>
<body style="background-image: url('../../common/image/bg-page.jpg'); background-size: cover;background-position: center; background-repeat: repeat-y;">
    <div class="topWrap">
        <div class="dash-profile">
            <a class="tab" href="@Url.Action("Index","Main")" data-aos="fade-down" data-aos-duration="2000">
                <span class="language">&nbspHOME</span>
            </a>
            <a class="tab" href="@Url.Action("Order_buy_point","Order")" data-aos="fade-down" data-aos-duration="2000">
                <span class="language">신청하기</span>
            </a>
            <a class="tab" href="~/Login/LogOut" data-aos="fade-down" data-aos-duration="2000">
                <span class="language">로그아웃</span>
            </a>
        </div>
        @RenderBody()

    </div>
    @Scripts.Render("~/common/script/Chart.min.js")
    @Scripts.Render("~/common/script/all.js")
    @Scripts.Render("~/common/script/jquery.custom.extend.js")
    @Scripts.Render("~/common/script/commonutil.js")
    @Scripts.Render("~/common/script/jquery.cookie.js")
    @Scripts.Render("~/common/script/clipboard.min.js")
    @RenderSection("scripts", required: false)
</body>
</html>

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_chart.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>MyOffice</title>

    <script src="~/vendor/chart/js/jquery.min.js"></script>
        <script src="~/vendor/chart/js/loader.js"></script>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        #chart {
            width: 900px;
            height: 500px;
        }

/*        #chart div {
            width: 100px;
        }*/

        #chart img {
            height: 90px;
            width: 90px;
        }
        .drop-level{
            padding: 7px;
            border-radius: 5px;
            border: none;
            color: #000;
            background: #f7da04;
        }
    </style>
</head>
<body style="background-image: url('../../common/image/bg-page.png');background-size: cover;margin: 0;">
    <header style="position: relative; top: 0; width: 100%; background: #0e0e0e; padding: 0px; margin: 0px; height:40px;">
    </header>
    @RenderBody()


</body>
</html>

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_login.cshtml
<!DOCTYPE html>
<html lang=ko>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--#include file="../common/header.asp"-->
    <title>태왕의사신기</title>
    <link rel="icon" href="../../common/image/logo.ico" type="image/gif" sizes="16x16">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    @Styles.Render("~/common/css/reset.min.css")
    @Styles.Render("~/common/css/pages/style.css")
    @Styles.Render("~/common/css/pages/login.css")
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>
<body style="display:flex; justify-content:center;">
    <div id="wrap" style="background-image:url('../../common/image/bg.jpg'); background-position:center;">
        <div id="container">
            @RenderBody()
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_none.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>MyOffice</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        #chart {
            width: 900px;
            height: 500px;
        }

            #chart div {
                width: 100px;
            }

            #chart img {
                height: 90px;
                width: 90px;
            }
    </style>
</head>
<body>
    @RenderBody()
</body>
</html>

AHC_DEV_05/AHC_DEV_05/Views/Shared/_Layout_regis.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>태왕의사신기</title>
    <link rel="icon" href="../../common/image/logo.ico" type="image/gif" sizes="16x16">
    @Styles.Render("~/common/css/reset.min.css")
    @Styles.Render("~/common/css/pages/gnb.css")
    @Styles.Render("~/common/css/pages/footer.css")
    @Styles.Render("~/common/css/main.css")

    @Styles.Render("~/common/css/reset-1.css")
    @Styles.Render("~/common/css/pages/style.css")

    @Scripts.Render("~/common/script/jquery-3.4.1.min.js")
    @Scripts.Render("~/common/script/jquery.custom.extend.js")
    @Scripts.Render("~/common/script/commonutil.js")
    @Scripts.Render("~/common/script/jquery.cookie.js")
    @Scripts.Render("~/common/script/clipboard.min.js")
</head>
<Body style="background:#000;>
    <div id="wrap" ">

        @RenderBody()
    </div>
    <!-- End of Main Content -->
    <!--JS Main-->
    @Scripts.Render("~/common/script/Chart.min.js")
    @Scripts.Render("~/common/script/all.js")
    @Scripts.Render("~/common/script/jquery.custom.extend.js")
    @Scripts.Render("~/common/script/commonutil.js")
    @Scripts.Render("~/common/script/jquery.cookie.js")
    @Scripts.Render("~/common/script/clipboard.min.js")
    @RenderSection("scripts", required: false)
</Body>
</html>